paths:
  humanml3d-mapping: "/Users/pazimor/repo/HumanML3D/index.csv"
  amass-root: "/Volumes/Code assets/AMASS"
  converted-root: "/Volumes/Code assets/converted_60"
  prompt-sources: "/Users/pazimor/repo/HumanML3D/HumanML3D/texts/texts"
  # supprimer proprement custom_prompt_files:
  output-root: "output/dataset"
processing:
  animation-extension: ".npz"
  prompt-text-extension: ".txt"
  fallback-fps: 60
